spring.application.name=library

# 🔌 Configurações de Conexão do PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-billowing-fog-ad7wtc09-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Co0gY9aTnSkE&sslmode=require&channelBinding=require
spring.datasource.username=seu_usuario_do_postgres
spring.datasource.password=sua_senha_do_postgres
spring.datasource.driverClassName=org.postgresql.Driver

# 🧠 Configurações do Hibernate / JPA para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# 📜 Logs do SQL no Console (Ótimo para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=sua-chave-secreta-e-segura-aqui